# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('partner_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('ad_content', models.TextField(max_length=1000)),
            ],
        ),
    ]
