# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='creation_time',
            field=models.TimeField(null=True),
        ),
    ]
