# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0002_campaign_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='creation_time',
            field=models.TimeField(default=datetime.datetime(2017, 7, 20, 6, 25, 57, 494104)),
        ),
    ]
