# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_app', '0003_auto_20170720_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='creation_time',
            field=models.TimeField(default=datetime.time(6, 29, 15, 507485)),
        ),
    ]
